MyIWallet/Models/Wallet.cs
using MyIWallet.Enums;

namespace MyIWallet.Models
{
    public class Wallet
    {
        public int Id { get; set; }

        public string UserId { get; set; }

        public TransactionType Type { get; set; }       


        public string? Description { get; set; }

        public decimal Amount { get; set; }            

        public DateTime CreationTime { get; set; }
    }

}

MyIWallet/ViewModels/BalanceViewModel.cs
using MyIWallet.Models;

namespace MyIWallet.ViewModels
{
    public class BalanceViewModel
    {
        public string Email { get; set; }

        public decimal Amount { get; set; }
        public IEnumerable<TransactionViewModel> Transactions { get; set; }

    }
}

MyIWallet/Controllers/WalletController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyIWallet.Contexts;
using MyIWallet.Interfaces;
using MyIWallet.Models;
using MyIWallet.ViewModels;

namespace MyIWallet.Controllers
{
    [Authorize]
    public class WalletController : Controller
    {
        private readonly ApplicationContext _applicationContext;
        private readonly UserManager<User> _userManager;
        private readonly ITransactionService _transactionService;

        public WalletController(
            ApplicationContext applicationContext,
            UserManager<User> userManager,
            ITransactionService transactionService)
        {
            _applicationContext = applicationContext;
            _userManager = userManager;
            _transactionService = transactionService;
        }


        [HttpGet]
        public async Task<IActionResult> Balance()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var wallets = await _applicationContext.Wallets
                .Where(wallet => wallet.UserId == user.Id)
                .ToListAsync();
            var userWallets = wallets
                .OrderByDescending(transaction => transaction.CreationTime)
                .ToList();

            var amount = decimal.Zero;
            if (userWallets.Any())
            {
                amount = _transactionService.CalculateBalance(userWallets);
            }

            var list = new List<TransactionViewModel>();
            foreach (var userWallet in userWallets)
            {
                var transactionViewModel = new TransactionViewModel
                {
                    CreationTime = userWallet.CreationTime,
                    Type = userWallet.Type,
                    Amount = userWallet.Amount,
                    Description = userWallet.Description,
                    Id = userWallet.Id,
                };
                list.Add(transactionViewModel);
            }

            var model = new BalanceViewModel
            {
                Email = user.Email,
                Amount = amount,
                Transactions = list,
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Transaction()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Transaction(TransactionViewModel model)       //IActionResult вмсето Task<IActionResult>
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);

                var log = new Wallet
                {
                    UserId = user.Id,
                    Type = model.Type,
                    Description = model.Description,
                    Amount = model.Amount,
                    CreationTime = DateTime.Now,
                };

                await _applicationContext.Wallets.AddAsync(log);
                await _applicationContext.SaveChangesAsync();

                return Redirect("Balance");
            }

            return View(model);

        }
    }
}

MyIWallet/Views/Wallet/Balance.cshtml
@model BalanceViewModel

<h3>Аккаунт пользователя = @Model.Email</h3>
<h3>Вданный момент в кошельке @Model.Amount</h3>

<div>
    <h3>История</h3>

    @if (Model.Transactions.Any())
    {
        <table>
            <tr>
                <th>Тип</th>
                <th>Сумма</th>
                <th>Описание</th>
                <th>Дата</th>
            </tr>

            @foreach (var item in Model.Transactions)
            {
                <tr>
                    <td>@item.Type</td>
                    <td>@item.Amount</td>
                    <td>@item.Description</td>
                    <td>@item.CreationTime</td>
                </tr>
            }

        </table>
    }
    else
    {
        <p>История пуста</p>
    }

</div>

@section Links{
    <link rel="stylesheet" href="~/css/Balance.css" asp-append-version="true" />
}
    

MyIWallet/Views/Wallet/Transaction.cshtml
@using MyIWallet.Enums;
@model TransactionViewModel

<h2>Добавить транзакцию</h2>
<form method="post" asp-controller="Wallet" asp-action="Transaction" enctype="multipart/form-data">

    <div class="transaction-form__type transaction-form__bottom">
        <p class="transaction-input__text--type">Type</p>
        <select id="Type" name="Type">
            <option value="Income">Доход</option>
            <option value="Expense">Расход</option>
        </select>
    </div>

    <div class="transaction-form__description transaction-form__bottom">
        <p class="transaction-input__text--description">Description</p>
        <textarea name="Description" cols="40" rows="3" class="transaction-input__description" placeholder="Description"></textarea>
    </div>

    <div class="transaction-form__amount transaction-form__bottom">
        <p class="transaction-input__text--amount">Amount</p>
        <input name="Amount" type="number" class="transaction-input__amount" placeholder="Amount" min="0">
    </div>

    <button type="submit">Send data</button>
</form>


        @*посмотреть нужно ли вообще JS ПОЛДКЛЮЧАТ  или вырезать *@
@section Scripts{
    <script src="~/js/cv-input.js" asp-append-version="true"></script>
}
@section Links{
    <link rel="stylesheet" href="~/css/Inp.css" asp-append-version="true" />
}